import { BloodInventory, BloodRequest, Donor, BloodType } from './types';

export const bloodInventory: BloodInventory[] = [
  { id: '1', bloodType: 'A+', units: 45, lastUpdated: new Date() },
  { id: '2', bloodType: 'A-', units: 12, lastUpdated: new Date() },
  { id: '3', bloodType: 'B+', units: 38, lastUpdated: new Date() },
  { id: '4', bloodType: 'B-', units: 8, lastUpdated: new Date() },
  { id: '5', bloodType: 'AB+', units: 15, lastUpdated: new Date() },
  { id: '6', bloodType: 'AB-', units: 5, lastUpdated: new Date() },
  { id: '7', bloodType: 'O+', units: 62, lastUpdated: new Date() },
  { id: '8', bloodType: 'O-', units: 18, lastUpdated: new Date() },
];

export const bloodRequests: BloodRequest[] = [
  {
    id: '1',
    patientName: 'Sarah Johnson',
    bloodType: 'A+',
    units: 2,
    hospital: 'City General Hospital',
    contactNumber: '555-0101',
    urgency: 'urgent',
    status: 'pending',
    requestedBy: 'user1',
    requestedAt: new Date(Date.now() - 86400000),
    notes: 'Surgery scheduled for tomorrow',
  },
  {
    id: '2',
    patientName: 'Michael Chen',
    bloodType: 'O-',
    units: 4,
    hospital: 'Memorial Medical Center',
    contactNumber: '555-0102',
    urgency: 'critical',
    status: 'approved',
    requestedBy: 'user2',
    requestedAt: new Date(Date.now() - 172800000),
    notes: 'Emergency trauma case',
  },
  {
    id: '3',
    patientName: 'Emily Davis',
    bloodType: 'B+',
    units: 1,
    hospital: 'St. Mary Hospital',
    contactNumber: '555-0103',
    urgency: 'normal',
    status: 'fulfilled',
    requestedBy: 'user3',
    requestedAt: new Date(Date.now() - 259200000),
  },
  {
    id: '4',
    patientName: 'Robert Wilson',
    bloodType: 'AB-',
    units: 3,
    hospital: 'University Hospital',
    contactNumber: '555-0104',
    urgency: 'urgent',
    status: 'pending',
    requestedBy: 'user4',
    requestedAt: new Date(Date.now() - 43200000),
    notes: 'Rare blood type needed',
  },
];

export const donors: Donor[] = [
  {
    id: '1',
    name: 'James Anderson',
    email: 'james.a@email.com',
    phone: '555-1001',
    bloodType: 'O+',
    lastDonation: new Date(Date.now() - 7776000000),
    totalDonations: 12,
    address: '123 Oak Street',
    isEligible: true,
  },
  {
    id: '2',
    name: 'Maria Garcia',
    email: 'maria.g@email.com',
    phone: '555-1002',
    bloodType: 'A+',
    lastDonation: new Date(Date.now() - 2592000000),
    totalDonations: 8,
    address: '456 Pine Avenue',
    isEligible: false,
  },
  {
    id: '3',
    name: 'David Thompson',
    email: 'david.t@email.com',
    phone: '555-1003',
    bloodType: 'B-',
    lastDonation: new Date(Date.now() - 15552000000),
    totalDonations: 5,
    address: '789 Elm Road',
    isEligible: true,
  },
  {
    id: '4',
    name: 'Lisa Martinez',
    email: 'lisa.m@email.com',
    phone: '555-1004',
    bloodType: 'AB+',
    lastDonation: null,
    totalDonations: 0,
    address: '321 Maple Drive',
    isEligible: true,
  },
  {
    id: '5',
    name: 'William Brown',
    email: 'william.b@email.com',
    phone: '555-1005',
    bloodType: 'O-',
    lastDonation: new Date(Date.now() - 10368000000),
    totalDonations: 20,
    address: '654 Cedar Lane',
    isEligible: true,
  },
];

export function getCompatibleBloodTypes(bloodType: BloodType): BloodType[] {
  const compatibility: Record<BloodType, BloodType[]> = {
    'A+': ['A+', 'A-', 'O+', 'O-'],
    'A-': ['A-', 'O-'],
    'B+': ['B+', 'B-', 'O+', 'O-'],
    'B-': ['B-', 'O-'],
    'AB+': ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    'AB-': ['A-', 'B-', 'AB-', 'O-'],
    'O+': ['O+', 'O-'],
    'O-': ['O-'],
  };
  return compatibility[bloodType];
}
